### ISSUE TITLE
how to create tx transfer use this sdk

### ISSUE THREAD

**Issue by malingzhao** [theQRL/go-qrl-legacy#232]

**Comment by cyyber** [comment]
go-qrl was the part of the Zond and work in progress for Proof of Stake consensus mechanism. It is no more the same as the currently running QRL mainnet ( https://github.com/theQRL/QRL ) which is running on Proof of Work consensus algorithm.

For the Proof of Stake (for which mainnet not yet released), you can look into the following link
https://test-zond.theqrl.org/transaction.html
https://github.com/theQRL/zond-contract-example/blob/%40theqrl/web3/1-deploy.js (example using web3 api)

For the Proof of Work (for which mainnet is released since 2018) you can look into
https://docs.theqrl.org/api/qrl-public-api#transfercoins
https://docs.theqrl.org/api/qrl-public-api#pushtransaction
